// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/proto/rubric.proto

package protoconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect_go "github.com/bufbuild/connect-go"
	proto "github.com/jh125486/CSCE5350_gradebot/pkg/proto"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// RubricServiceName is the fully-qualified name of the RubricService service.
	RubricServiceName = "rubric.RubricService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RubricServiceUploadRubricResultProcedure is the fully-qualified name of the RubricService's
	// UploadRubricResult RPC.
	RubricServiceUploadRubricResultProcedure = "/rubric.RubricService/UploadRubricResult"
)

// RubricServiceClient is a client for the rubric.RubricService service.
type RubricServiceClient interface {
	UploadRubricResult(context.Context, *connect_go.Request[proto.UploadRubricResultRequest]) (*connect_go.Response[proto.UploadRubricResultResponse], error)
}

// NewRubricServiceClient constructs a client for the rubric.RubricService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRubricServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) RubricServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &rubricServiceClient{
		uploadRubricResult: connect_go.NewClient[proto.UploadRubricResultRequest, proto.UploadRubricResultResponse](
			httpClient,
			baseURL+RubricServiceUploadRubricResultProcedure,
			opts...,
		),
	}
}

// rubricServiceClient implements RubricServiceClient.
type rubricServiceClient struct {
	uploadRubricResult *connect_go.Client[proto.UploadRubricResultRequest, proto.UploadRubricResultResponse]
}

// UploadRubricResult calls rubric.RubricService.UploadRubricResult.
func (c *rubricServiceClient) UploadRubricResult(ctx context.Context, req *connect_go.Request[proto.UploadRubricResultRequest]) (*connect_go.Response[proto.UploadRubricResultResponse], error) {
	return c.uploadRubricResult.CallUnary(ctx, req)
}

// RubricServiceHandler is an implementation of the rubric.RubricService service.
type RubricServiceHandler interface {
	UploadRubricResult(context.Context, *connect_go.Request[proto.UploadRubricResultRequest]) (*connect_go.Response[proto.UploadRubricResultResponse], error)
}

// NewRubricServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRubricServiceHandler(svc RubricServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	rubricServiceUploadRubricResultHandler := connect_go.NewUnaryHandler(
		RubricServiceUploadRubricResultProcedure,
		svc.UploadRubricResult,
		opts...,
	)
	return "/rubric.RubricService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RubricServiceUploadRubricResultProcedure:
			rubricServiceUploadRubricResultHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRubricServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRubricServiceHandler struct{}

func (UnimplementedRubricServiceHandler) UploadRubricResult(context.Context, *connect_go.Request[proto.UploadRubricResultRequest]) (*connect_go.Response[proto.UploadRubricResultResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("rubric.RubricService.UploadRubricResult is not implemented"))
}
